export const GRIDEX_ABI = [
  // Events
  {
    type: 'event',
    name: 'GridOrderCreated',
    inputs: [
      { name: 'maker', type: 'address', indexed: true },
      { name: 'pairId', type: 'uint64', indexed: true },
      { name: 'baseAmount', type: 'uint128', indexed: false },
      { name: 'gridId', type: 'uint128', indexed: false },
      { name: 'startAskOrderId', type: 'uint256', indexed: false },
      { name: 'startBidOrderId', type: 'uint256', indexed: false },
      { name: 'askOrderCount', type: 'uint32', indexed: false },
      { name: 'bidOrderCount', type: 'uint32', indexed: false },
      { name: 'fee', type: 'uint32', indexed: false },
      { name: 'compound', type: 'bool', indexed: false },
      { name: 'oneshot', type: 'bool', indexed: false },
    ],
  },
  {
    type: 'event',
    name: 'FilledOrder',
    inputs: [
      { name: 'taker', type: 'address', indexed: true },
      { name: 'gridOrderId', type: 'uint256', indexed: true },
      { name: 'filledAmt', type: 'uint128', indexed: false },
      { name: 'filledVol', type: 'uint128', indexed: false },
      { name: 'orderAmt', type: 'uint128', indexed: false },
      { name: 'orderRevAmt', type: 'uint128', indexed: false },
      { name: 'isAsk', type: 'bool', indexed: false },
    ],
  },
  {
    type: 'event',
    name: 'WithdrawProfit',
    inputs: [
      { name: 'gridId', type: 'uint128', indexed: true },
      { name: 'quote', type: 'address', indexed: false },
      { name: 'to', type: 'address', indexed: false },
      { name: 'amt', type: 'uint256', indexed: false },
    ],
  },
  // Read functions
  {
    type: 'function',
    name: 'getGridOrder',
    stateMutability: 'view',
    inputs: [{ name: 'id', type: 'uint256' }],
    outputs: [
      {
        name: 'order',
        type: 'tuple',
        components: [
          { name: 'isAsk', type: 'bool' },
          { name: 'compound', type: 'bool' },
          { name: 'oneshot', type: 'bool' },
          { name: 'fee', type: 'uint32' },
          { name: 'status', type: 'uint32' },
          { name: 'gridId', type: 'uint128' },
          { name: 'orderId', type: 'uint128' },
          { name: 'amount', type: 'uint128' },
          { name: 'revAmount', type: 'uint128' },
          { name: 'baseAmt', type: 'uint128' },
          { name: 'price', type: 'uint256' },
          { name: 'revPrice', type: 'uint256' },
          { name: 'pairId', type: 'uint64' },
        ],
      },
    ],
  },
  {
    type: 'function',
    name: 'getGridOrders',
    stateMutability: 'view',
    inputs: [{ name: 'idList', type: 'uint256[]' }],
    outputs: [
      {
        name: '',
        type: 'tuple[]',
        components: [
          { name: 'isAsk', type: 'bool' },
          { name: 'compound', type: 'bool' },
          { name: 'oneshot', type: 'bool' },
          { name: 'fee', type: 'uint32' },
          { name: 'status', type: 'uint32' },
          { name: 'gridId', type: 'uint128' },
          { name: 'orderId', type: 'uint128' },
          { name: 'amount', type: 'uint128' },
          { name: 'revAmount', type: 'uint128' },
          { name: 'baseAmt', type: 'uint128' },
          { name: 'price', type: 'uint256' },
          { name: 'revPrice', type: 'uint256' },
          { name: 'pairId', type: 'uint64' },
        ],
      },
    ],
  },
  {
    type: 'function',
    name: 'getGridProfits',
    stateMutability: 'view',
    inputs: [{ name: 'gridId', type: 'uint96' }],
    outputs: [{ name: '', type: 'uint256' }],
  },
  {
    type: 'function',
    name: 'getGridConfig',
    stateMutability: 'view',
    inputs: [{ name: 'gridId', type: 'uint96' }],
    outputs: [
      {
        name: '',
        type: 'tuple',
        components: [
          { name: 'owner', type: 'address' },
          { name: 'askStrategy', type: 'address' },
          { name: 'bidStrategy', type: 'address' },
          { name: 'profits', type: 'uint128' },
          { name: 'baseAmt', type: 'uint128' },
          { name: 'startAskOrderId', type: 'uint128' },
          { name: 'startBidOrderId', type: 'uint128' },
          { name: 'gridId', type: 'uint128' },
          { name: 'pairId', type: 'uint64' },
          { name: 'askOrderCount', type: 'uint32' },
          { name: 'bidOrderCount', type: 'uint32' },
          { name: 'fee', type: 'uint32' },
          { name: 'compound', type: 'bool' },
          { name: 'oneshot', type: 'bool' },
          { name: 'status', type: 'uint32' },
        ],
      },
    ],
  },
  // Write functions
  {
    type: 'function',
    name: 'placeGridOrders',
    stateMutability: 'nonpayable',
    inputs: [
      { name: 'base', type: 'address' },
      { name: 'quote', type: 'address' },
      {
        name: 'param',
        type: 'tuple',
        components: [
          { name: 'askStrategy', type: 'address' },
          { name: 'bidStrategy', type: 'address' },
          { name: 'askData', type: 'bytes' },
          { name: 'bidData', type: 'bytes' },
          { name: 'askOrderCount', type: 'uint32' },
          { name: 'bidOrderCount', type: 'uint32' },
          { name: 'fee', type: 'uint32' },
          { name: 'compound', type: 'bool' },
          { name: 'oneshot', type: 'bool' },
          { name: 'baseAmount', type: 'uint128' },
        ],
      },
    ],
    outputs: [],
  },
  {
    type: 'function',
    name: 'placeETHGridOrders',
    stateMutability: 'payable',
    inputs: [
      { name: 'base', type: 'address' },
      { name: 'quote', type: 'address' },
      {
        name: 'param',
        type: 'tuple',
        components: [
          { name: 'askStrategy', type: 'address' },
          { name: 'bidStrategy', type: 'address' },
          { name: 'askData', type: 'bytes' },
          { name: 'bidData', type: 'bytes' },
          { name: 'askOrderCount', type: 'uint32' },
          { name: 'bidOrderCount', type: 'uint32' },
          { name: 'fee', type: 'uint32' },
          { name: 'compound', type: 'bool' },
          { name: 'oneshot', type: 'bool' },
          { name: 'baseAmount', type: 'uint128' },
        ],
      },
    ],
    outputs: [],
  },
  {
    type: 'function',
    name: 'cancelGrid',
    stateMutability: 'nonpayable',
    inputs: [
      { name: 'recipient', type: 'address' },
      { name: 'gridId', type: 'uint128' },
      { name: 'flag', type: 'uint32' },
    ],
    outputs: [],
  },
  {
    type: 'function',
    name: 'withdrawGridProfits',
    stateMutability: 'nonpayable',
    inputs: [
      { name: 'gridId', type: 'uint128' },
      { name: 'amt', type: 'uint256' },
      { name: 'to', type: 'address' },
      { name: 'flag', type: 'uint32' },
    ],
    outputs: [],
  },
  {
    type: 'function',
    name: 'modifyGridFee',
    stateMutability: 'nonpayable',
    inputs: [
      { name: 'gridId', type: 'uint128' },
      { name: 'fee', type: 'uint32' },
    ],
    outputs: [],
  },
] as const;
